-- MySQL Script generated by MySQL Workbench
-- Mon Dec 18 12:44:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `animes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `animes` ;

CREATE TABLE IF NOT EXISTS `animes` (
  `id` INT NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `Synopsis` LONGTEXT NULL,
  `Background` VARCHAR(45) NULL,
  `imgnames` VARCHAR(45) NOT NULL,
  `details` LONGTEXT NOT NULL,
  `youtubelink` VARCHAR(45) NOT NULL,
  `adddate` VARCHAR(45) NULL,
  `animecode` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `character`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `character` ;

CREATE TABLE IF NOT EXISTS `character` (
  `id` INT NOT NULL,
  `animecode` VARCHAR(45) NULL,
  `charactername` VARCHAR(45) NULL,
  `character japon name` VARCHAR(45) NULL,
  `about` VARCHAR(800) NULL,
  `position` VARCHAR(45) NULL,
  `imgsource` VARCHAR(200) NULL,
  `details` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `genres` ;

CREATE TABLE IF NOT EXISTS `genres` (
  `id` INT NOT NULL,
  `animeid` VARCHAR(45) NULL,
  `gener` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mesages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mesages` ;

CREATE TABLE IF NOT EXISTS `mesages` (
  `id` INT NOT NULL,
  `userid` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  `mesagescol` VARCHAR(45) NULL,
  `text` VARCHAR(45) NULL,
  `like` VARCHAR(45) NULL,
  `animecode` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `themes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `themes` ;

CREATE TABLE IF NOT EXISTS `themes` (
  `id` INT NOT NULL,
  `animeid` VARCHAR(45) NULL,
  `theme` VARCHAR(45) NULL,
  `animes_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `usercode` VARCHAR(45) NULL,
  `commentpoint` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
